//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASA_WEB.ServiciosDGAC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="ServiciosDGAC.ServiciosDGAC")]
    public interface ServiciosDGAC {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento matricula del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioAeronaveRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioAeronaveResponse")]
        CASA_WEB.ServiciosDGAC.ServicioAeronaveResponse ServicioAeronave(CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioAeronaveRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioAeronaveResponse")]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioAeronaveResponse> ServicioAeronaveAsync(CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://WS/).
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioPilotoHabilitadoRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioPilotoHabilitadoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoResponse ServicioPilotoHabilitado(CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioPilotoHabilitadoRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioPilotoHabilitadoResponse")]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoResponse> ServicioPilotoHabilitadoAsync(CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://WS/).
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioPilotoExisteRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioPilotoExisteResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CASA_WEB.ServiciosDGAC.ServicioPilotoExisteResponse ServicioPilotoExiste(CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioPilotoExisteRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioPilotoExisteResponse")]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoExisteResponse> ServicioPilotoExisteAsync(CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://WS/).
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioPilotoMultaRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioPilotoMultaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CASA_WEB.ServiciosDGAC.ServicioPilotoMultaResponse ServicioPilotoMulta(CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiciosDGAC/ServicioPilotoMultaRequest", ReplyAction="http://WS/ServiciosDGAC/ServicioPilotoMultaResponse")]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoMultaResponse> ServicioPilotoMultaAsync(CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioAeronaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioAeronave", Namespace="http://WS/", Order=0)]
        public CASA_WEB.ServiciosDGAC.ServicioAeronaveRequestBody Body;
        
        public ServicioAeronaveRequest() {
        }
        
        public ServicioAeronaveRequest(CASA_WEB.ServiciosDGAC.ServicioAeronaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ServicioAeronaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string matricula;
        
        public ServicioAeronaveRequestBody() {
        }
        
        public ServicioAeronaveRequestBody(string matricula) {
            this.matricula = matricula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioAeronaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioAeronaveResponse", Namespace="http://WS/", Order=0)]
        public CASA_WEB.ServiciosDGAC.ServicioAeronaveResponseBody Body;
        
        public ServicioAeronaveResponse() {
        }
        
        public ServicioAeronaveResponse(CASA_WEB.ServiciosDGAC.ServicioAeronaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ServicioAeronaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ServicioAeronaveResponseBody() {
        }
        
        public ServicioAeronaveResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioPilotoHabilitado", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class ServicioPilotoHabilitadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int rut;
        
        public ServicioPilotoHabilitadoRequest() {
        }
        
        public ServicioPilotoHabilitadoRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioPilotoHabilitadoResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class ServicioPilotoHabilitadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public ServicioPilotoHabilitadoResponse() {
        }
        
        public ServicioPilotoHabilitadoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioPilotoExiste", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class ServicioPilotoExisteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int rut;
        
        public ServicioPilotoExisteRequest() {
        }
        
        public ServicioPilotoExisteRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioPilotoExisteResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class ServicioPilotoExisteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public ServicioPilotoExisteResponse() {
        }
        
        public ServicioPilotoExisteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioPilotoMulta", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class ServicioPilotoMultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int rut;
        
        public ServicioPilotoMultaRequest() {
        }
        
        public ServicioPilotoMultaRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioPilotoMultaResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class ServicioPilotoMultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public ServicioPilotoMultaResponse() {
        }
        
        public ServicioPilotoMultaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosDGACChannel : CASA_WEB.ServiciosDGAC.ServiciosDGAC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosDGACClient : System.ServiceModel.ClientBase<CASA_WEB.ServiciosDGAC.ServiciosDGAC>, CASA_WEB.ServiciosDGAC.ServiciosDGAC {
        
        public ServiciosDGACClient() {
        }
        
        public ServiciosDGACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosDGACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDGACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDGACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CASA_WEB.ServiciosDGAC.ServicioAeronaveResponse CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioAeronave(CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest request) {
            return base.Channel.ServicioAeronave(request);
        }
        
        public string ServicioAeronave(string matricula) {
            CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest();
            inValue.Body = new CASA_WEB.ServiciosDGAC.ServicioAeronaveRequestBody();
            inValue.Body.matricula = matricula;
            CASA_WEB.ServiciosDGAC.ServicioAeronaveResponse retVal = ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioAeronave(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioAeronaveResponse> CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioAeronaveAsync(CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest request) {
            return base.Channel.ServicioAeronaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioAeronaveResponse> ServicioAeronaveAsync(string matricula) {
            CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioAeronaveRequest();
            inValue.Body = new CASA_WEB.ServiciosDGAC.ServicioAeronaveRequestBody();
            inValue.Body.matricula = matricula;
            return ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioAeronaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoResponse CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioPilotoHabilitado(CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest request) {
            return base.Channel.ServicioPilotoHabilitado(request);
        }
        
        public bool ServicioPilotoHabilitado(int rut) {
            CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest();
            inValue.rut = rut;
            CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoResponse retVal = ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioPilotoHabilitado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoResponse> CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioPilotoHabilitadoAsync(CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest request) {
            return base.Channel.ServicioPilotoHabilitadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoResponse> ServicioPilotoHabilitadoAsync(int rut) {
            CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioPilotoHabilitadoRequest();
            inValue.rut = rut;
            return ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioPilotoHabilitadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CASA_WEB.ServiciosDGAC.ServicioPilotoExisteResponse CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioPilotoExiste(CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest request) {
            return base.Channel.ServicioPilotoExiste(request);
        }
        
        public bool ServicioPilotoExiste(int rut) {
            CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest();
            inValue.rut = rut;
            CASA_WEB.ServiciosDGAC.ServicioPilotoExisteResponse retVal = ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioPilotoExiste(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoExisteResponse> CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioPilotoExisteAsync(CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest request) {
            return base.Channel.ServicioPilotoExisteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoExisteResponse> ServicioPilotoExisteAsync(int rut) {
            CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioPilotoExisteRequest();
            inValue.rut = rut;
            return ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioPilotoExisteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CASA_WEB.ServiciosDGAC.ServicioPilotoMultaResponse CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioPilotoMulta(CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest request) {
            return base.Channel.ServicioPilotoMulta(request);
        }
        
        public bool ServicioPilotoMulta(int rut) {
            CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest();
            inValue.rut = rut;
            CASA_WEB.ServiciosDGAC.ServicioPilotoMultaResponse retVal = ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioPilotoMulta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoMultaResponse> CASA_WEB.ServiciosDGAC.ServiciosDGAC.ServicioPilotoMultaAsync(CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest request) {
            return base.Channel.ServicioPilotoMultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CASA_WEB.ServiciosDGAC.ServicioPilotoMultaResponse> ServicioPilotoMultaAsync(int rut) {
            CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest inValue = new CASA_WEB.ServiciosDGAC.ServicioPilotoMultaRequest();
            inValue.rut = rut;
            return ((CASA_WEB.ServiciosDGAC.ServiciosDGAC)(this)).ServicioPilotoMultaAsync(inValue);
        }
    }
}
